### PR TITLE
[FEAT] - Implemented Workflow for First PR and First Issue

### LINKED ISSUE #30: 💡 [FEATURE] - Create a Workflow for First PR and First Issue
### Description:
Develop a workflow to acknowledge and celebrate the creators of the first Pull Request (PR) and the first Issue in our project. This workflow should be designed to recognize their contributions and encourage further participation.

### Tasks:
- [ ] Create the workflow for the first PR and first Issue using a `.yml` file.
- [ ] Add the created workflow to the `.github/workflows` directory.
- [ ] Test the workflow to ensure it functions as intended.

### PR DESCRIPTION
**Pull request by Petsamuel**
resolve #30

### CODE REVIEW

**Comment by Pinaka-Pani-18** [comment]
Hi @

> resolve #30

Hi @Petsamuel, the two files contain same code, is it right?

**Review by Pinaka-Pani-18 — APPROVED** [review]
Please don't forget to star the repo if you enjoy contributing to the project.

**Comment by Petsamuel** [comment]
> Hi @
> 
> > resolve #30
> 
> Hi @Petsamuel, the two files contain same code, is it right?

Yes they are, 
I thought I got rid of one of them...
I'm sorry about that

**Comment by Petsamuel** [comment]
> Please don't forget to star the repo if you enjoy contributing to the project.

Sure

**Pull request merged**
