### PR TITLE
feat:project page cards implemented

### PR DESCRIPTION
**Pull request by akash0708**
# Issue #13 

Hello @Pinaka-Pani-18 , I've started working on the projects page, and opened this pull request to keep you updated. I will keep updating you here and you can suggest any changes you want me to add. As of now, I have created the cards. I am working on the search bar now.

### CODE REVIEW

**Review by Pinaka-Pani-18 — APPROVED** [review]
Great work, @akash0708! 
One suggestion:
    Create a .json file or an array and map through it so that anyone can add their projects by including the respective fields.

**Comment by akash0708** [comment]
@Pinaka-Pani-18 , alright I will do that then, once I am done with the search bar!

**Comment by Pinaka-Pani-18** [comment]
> @Pinaka-Pani-18 , alright I will do that then, once I am done with the search bar!

okay, make a separate pull request (PR) after making the necessary changes.

**Comment by akash0708** [comment]
@Pinaka-Pani-18 , why does the official website say that the repo has been excluded?

image

**Comment by Pinaka-Pani-18** [comment]
> @Pinaka-Pani-18 , why does the official website say that the repo has been excluded?
> 
> image

Hello @akash0708 , this repo has been excluded from Hacktoberfest, but I'm not sure of the reason. I suspect it might have been reported. As a result, I have created the same project [here](https://github.com/Pinaka-Pani-18/Public-Codebases). I'll create an issue there, and you can comment on it and make the necessary changes. Afterward, you can create a PR.

**Pull request merged**
